"""Constants for Deye Energy Manager."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "deye_energy_manager"
NAME = "Deye Energy Manager"

PLATFORMS = ["sensor", "binary_sensor", "switch", "select", "number", "button"]

DEFAULT_SCAN_INTERVAL = timedelta(seconds=30)
STARTUP_GRACE = timedelta(seconds=60)
WRITE_RATE_LIMIT = timedelta(seconds=60)

CONF_ENTITY_MAP = "entity_map"
CONF_HEAT_LOADS = "heat_loads"

THERMAL_MODE_OPTIONS = ["heating", "cooling", "auto", "off"]
DEFAULT_THERMAL_MODE = "heating"
THERMAL_ACTUATION_MODE_OPTIONS = ["advisory", "direct"]
DEFAULT_THERMAL_ACTUATION_MODE = "advisory"
FLEXIBLE_LOAD_PRIORITY_OPTIONS = ["battery_first", "thermal_before_ev", "ev_before_thermal", "export_before_loads"]
DEFAULT_FLEXIBLE_LOAD_PRIORITY = "battery_first"
FAN_MODE_OPTIONS = ["auto", "low", "medium", "high", "quiet"]
FAN_MODE_DEFAULTS = {
    "heat_soak_fan_mode": "high",
    "heat_normal_fan_mode": "low",
    "cool_soak_fan_mode": "high",
    "cool_normal_fan_mode": "low",
    "morning_preheat_fan_mode": "low",
}

DEFAULT_ENTITY_MAP = {
    "battery_soc": "sensor.deye_battery_soc",
    "primary_soc_entity": "sensor.deye_battery_soc",
    "fallback_soc_entity": "input_number.deye_battery_soc_last_good",
    "fallback_soc_timestamp_entity": "input_datetime.deye_battery_soc_last_good_updated",
    "battery_power": "sensor.deye_battery_power",
    "grid_ct_power": "sensor.deye_grid_ct_power",
    "essential_power": "sensor.deye_essential_power",
    "battery_rated_capacity": "sensor.deye_battery_rated_capacity",
    "battery_voltage": "sensor.deye_battery_voltage",
    "forecast_today": "sensor.solcast_pv_forecast_forecast_today",
    "forecast_remaining_today": "sensor.solcast_pv_forecast_forecast_remaining_today",
    "forecast_tomorrow": "sensor.solcast_pv_forecast_forecast_tomorrow",
    "pv_power_now": "sensor.solcast_pv_forecast_power_now",
    "pv_power_in_30_minutes": "sensor.solcast_pv_forecast_power_in_30_minutes",
    "pv_power_in_1_hour": "sensor.solcast_pv_forecast_power_in_1_hour",
    "grid_charge_switch": "switch.deye_grid_charge_enabled",
    "porsche_soc": "sensor.cayenne_e_hybrid_my24_state_of_charge",
    "porsche_charging_status": "sensor.cayenne_e_hybrid_my24_charging_status",
    "porsche_charging_ends": "sensor.cayenne_e_hybrid_my24_charging_ends",
    "porsche_charging_power": "sensor.cayenne_e_hybrid_my24_charging_power",
    "ev_power": "",
    "outdoor_temperature": "",
    "indoor_average_temperature": "",
    "home_occupancy": "",
}

DEFAULT_HEAT_LOADS = [
    {
        "slug": "dining",
        "name": "Dining/living heat pump",
        "climate_entity": "climate.diningheatpump_mqtt_hvac",
        "ownership_entity": "input_boolean.solar_owns_dining_heatpump",
        "priority": 1,
        "estimated_load_w": 2500,
        "hvac_mode": "heat",
        "target_temp": 23,
        "type": "heatpump",
        "enabled": True,
        "supports_heating": True,
        "supports_cooling": True,
        "allow_solar_soak": True,
        "comfort_sensor_type": "air",
        "active_power_threshold_w": 800,
        "idle_power_threshold_w": 150,
        "taper_power_threshold_w": 400,
        "allow_unowned_battery_shed": True,
        "never_emergency_shed": False,
    },
    {
        "slug": "underfloor",
        "name": "Bathroom underfloor",
        "climate_entity": "climate.master_bathroom_underfloor_heating",
        "ownership_entity": "input_boolean.solar_owns_underfloor",
        "priority": 2,
        "estimated_load_w": 800,
        "hvac_mode": "heat",
        "target_temp": 24,
        "type": "floor_underfloor",
        "enabled": True,
        "supports_heating": True,
        "supports_cooling": False,
        "allow_solar_soak": False,
        "comfort_sensor_type": "floor_slab",
        "comfort_min_temp": 9,
        "comfort_target_temp": 12,
        "normal_target_temp": 12,
        "max_target_temp": 14,
        "active_power_threshold_w": 200,
        "idle_power_threshold_w": 50,
        "taper_power_threshold_w": 100,
        "allow_unowned_battery_shed": False,
        "never_emergency_shed": False,
    },
    {
        "slug": "office",
        "name": "Office heat pump",
        "climate_entity": "climate.office_heatpump",
        "ownership_entity": "input_boolean.solar_owns_office_heatpump",
        "priority": 3,
        "estimated_load_w": 1800,
        "hvac_mode": "heat",
        "target_temp": 22,
        "type": "heatpump",
        "enabled": True,
        "supports_heating": True,
        "supports_cooling": True,
        "allow_solar_soak": True,
        "comfort_sensor_type": "air",
        "active_power_threshold_w": 800,
        "idle_power_threshold_w": 150,
        "taper_power_threshold_w": 400,
        "allow_unowned_battery_shed": True,
        "never_emergency_shed": False,
    },
    {
        "slug": "bedroom",
        "name": "Bedroom heat pump",
        "climate_entity": "climate.bedroom_heatpump",
        "ownership_entity": "input_boolean.solar_owns_bedroom_heatpump",
        "priority": 4,
        "estimated_load_w": 1800,
        "hvac_mode": "heat",
        "target_temp": 21,
        "type": "heatpump",
        "enabled": True,
        "supports_heating": True,
        "supports_cooling": True,
        "allow_solar_soak": True,
        "comfort_sensor_type": "air",
        "active_power_threshold_w": 800,
        "idle_power_threshold_w": 150,
        "taper_power_threshold_w": 400,
        "allow_unowned_battery_shed": True,
        "never_emergency_shed": False,
    },
    {
        "slug": "hallway",
        "name": "Hallway heat pump",
        "climate_entity": "climate.hallwayheatpump_mqtt_hvac",
        "ownership_entity": "input_boolean.solar_owns_hallway_heatpump",
        "priority": 5,
        "estimated_load_w": 1800,
        "hvac_mode": "heat",
        "target_temp": 21,
        "type": "heatpump",
        "enabled": True,
        "supports_heating": True,
        "supports_cooling": True,
        "allow_solar_soak": True,
        "comfort_sensor_type": "air",
        "active_power_threshold_w": 800,
        "idle_power_threshold_w": 150,
        "taper_power_threshold_w": 400,
        "allow_unowned_battery_shed": True,
        "never_emergency_shed": False,
    },
]

PROG_CAPACITY_ENTITIES = [
    "number.deye_prog1_capacity",
    "number.deye_prog2_capacity",
    "number.deye_prog3_capacity",
    "number.deye_prog4_capacity",
    "number.deye_prog5_capacity",
    "number.deye_prog6_capacity",
]

PROG_POWER_ENTITIES = [
    "number.deye_prog1_power",
    "number.deye_prog2_power",
    "number.deye_prog3_power",
    "number.deye_prog4_power",
    "number.deye_prog5_power",
    "number.deye_prog6_power",
]

PROG_CHARGE_SELECT_ENTITIES = [
    "select.deye_prog1_charge",
    "select.deye_prog2_charge",
    "select.deye_prog3_charge",
    "select.deye_prog4_charge",
    "select.deye_prog5_charge",
    "select.deye_prog6_charge",
]

FEATURE_DEFAULTS = {
    "enabled": True,
    "advisory_enabled": True,
    "deye_control_enabled": False,
    "grid_charge_control_enabled": False,
    "cheap_grid_preserve_enabled": True,
    "cheap_grid_charge_enabled": True,
    "ev_control_enabled": False,
    "ev_grid_bypass_enabled": False,
    "ev_solar_charging_enabled": False,
    "ev_cheap_grid_charging_enabled": True,
    "heat_control_enabled": False,
    "thermal_control_enabled": False,
    "direct_climate_control_enabled": False,
    "pv_load_test_control_enabled": False,
    "export_limited_mode_enabled": False,
    "return_to_normal_on_shed_enabled": True,
    "forecast_full_override_enabled": True,
    "thermal_rotation_enabled": True,
    "shed_unowned_managed_loads_on_battery_discharge": False,
    "morning_preheat_enabled": True,
    "passive_warming_guard_enabled": True,
    "paid_time_grid_avoidance_enabled": True,
    "underfloor_schedule_enabled": True,
    "underfloor_require_home": True,
    "underfloor_allow_paid_grid": False,
    "dynamic_base_load_estimate_enabled": True,
    "auto_mode_month_fallback_enabled": True,
}

NUMBER_DEFAULTS = {
    "heat_add_min_charge_w": 6000.0,
    "heat_add_min_soc": 80.0,
    "heat_shed_discharge_w": 500.0,
    "heat_soak_target_temp": 27.0,
    "heat_normal_target_temp": 21.0,
    "cool_soak_target_temp": 18.0,
    "cool_normal_target_temp": 24.0,
    "heat_comfort_target_temp": 21.0,
    "cool_comfort_target_temp": 24.0,
    "comfort_min_room_temp": 19.0,
    "full_soak_min_soc": 90.0,
    "forecast_soak_min_soc": 75.0,
    "morning_battery_priority_soc": 70.0,
    "morning_preheat_start_hour": 7.0,
    "morning_preheat_end_hour": 9.0,
    "morning_preheat_min_room_temp": 18.5,
    "morning_preheat_target_temp": 21.0,
    "morning_preheat_min_soc": 40.0,
    "morning_preheat_max_grid_import_w": 500.0,
    "morning_preheat_forecast_buffer_kwh": 3.0,
    "paid_time_min_reserve_soc": 40.0,
    "morning_paid_time_min_reserve_soc": 45.0,
    "evening_paid_time_min_reserve_soc": 30.0,
    "pre_peak_preserve_min_reserve_soc": 75.0,
    "paid_grid_import_threshold_w": 500.0,
    "paid_grid_import_grace_minutes": 2.0,
    "paid_time_discharge_margin_soc": 2.0,
    "cheap_grid_recharge_hysteresis_soc": 5.0,
    "cheap_grid_target_increase_hysteresis_soc": 3.0,
    "solar_arrived_charge_threshold_w": 1500.0,
    "solar_arrived_pv_surplus_threshold_w": 1000.0,
    "daily_battery_target_soc": 100.0,
    "battery_charge_efficiency": 0.94,
    "base_load_estimate_w": 1200.0,
    "base_load_window_minutes": 30.0,
    "house_load_forecast_buffer_kwh": 1.5,
    "solar_soak_required_battery_margin_kwh": 1.0,
    "paid_grid_avoidance_buffer_kwh": 1.0,
    "underfloor_morning_start_hour": 7.0,
    "underfloor_morning_end_hour": 9.0,
    "underfloor_evening_start_hour": 16.0,
    "underfloor_evening_end_hour": 24.0,
    "underfloor_preheat_minutes": 60.0,
    "underfloor_comfort_min_temp": 9.0,
    "underfloor_comfort_target_temp": 12.0,
    "underfloor_max_target_temp": 14.0,
    "underfloor_min_soc": 40.0,
    "underfloor_max_grid_import_w": 500.0,
    "thermal_start_min_soc": 80.0,
    "thermal_start_min_charge_w": 6000.0,
    "thermal_keep_running_min_charge_w": 1500.0,
    "thermal_export_start_w": 1000.0,
    "thermal_export_keep_w": 300.0,
    "thermal_export_import_tolerance_w": 300.0,
    "thermal_shed_discharge_w": 500.0,
    "thermal_emergency_shed_w": 2500.0,
    "room_satisfied_delta_c": 0.7,
    "room_resume_delta_c": 1.5,
    "forecast_full_confidence_buffer_kwh": 3.0,
    "ev_start_load_jump_w": 5000.0,
    "ev_stop_load_drop_w": 6000.0,
    "ev_active_load_threshold_w": 1000.0,
    "ev_stopped_load_threshold_w": 300.0,
    "ev_hold_extra_minutes": 10.0,
    "ev_fallback_hold_minutes": 180.0,
    "ev_restore_program_power_w": 12000.0,
    "min_thermal_run_minutes": 20.0,
    "min_thermal_rest_minutes": 10.0,
    "thermal_rotation_cooldown_minutes": 15.0,
    "auto_heating_below_temp": 16.0,
    "auto_cooling_above_temp": 24.0,
    "forecast_safety_buffer_kwh": 2.0,
    "min_soc_floor": 12.0,
    "max_grid_charge_target_soc": 80.0,
    "evening_peak_soc_target": 65.0,
    "evening_peak_heating_allowance_kwh": 4.0,
    "evening_peak_ev_allowance_kwh": 0.0,
    "cheap_grid_preserve_soc": 30.0,
    "cheap_grid_charge_target_soc": 60.0,
    "pv_load_test_min_soc": 70.0,
    "pv_load_test_min_expected_power_w": 4000.0,
    "pv_load_test_max_battery_charge_w": 2500.0,
    "pv_load_test_min_remaining_forecast_kwh": 8.0,
    "heat_satisfied_margin_c": 0.5,
    "heat_need_margin_c": 1.0,
    "manual_override_cooldown_min": 60.0,
    "emergency_shed_discharge_w": 4000.0,
    "battery_capacity_kwh": 30.0,
    "overnight_bedroom_taper_target_temp": 18.0,
    "max_fallback_soc_age_minutes": 360.0,
}

STRATEGY_OPTIONS = ["off", "conservative", "normal", "aggressive", "manual"]
DEFAULT_STRATEGY = "normal"

HEAT_MODE_OPTIONS = ["off", "advisory", "auto_direct"]
DEFAULT_HEAT_MODE = "advisory"

CHARGE_OPTION_NO_GRID = "No Grid or Gen"
CHARGE_OPTION_ALLOW_GRID = "Allow Grid"
